# ---
# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: go-demo-7
#   namespace: go-demo-7
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: go-demo-7-primary
#   minReplicas: 3
#   maxReplicas: 10
#   metrics:
#     - type: Object
#       object:
#         metricName: tps_service_requests
#         target:
#           apiVersion: v1
#           kind: Service
#           name: go-demo-7
#         targetValue: 50m
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: go-demo-7
  namespace: go-demo-7
  annotations:
    # metric-config.<metricType>.<metricName>.<collectorName>/<configKey>
    # metric-config.object.istio-requests-per-replica.prometheus/per-replica: "true" #note: this will automaticaly generate average per pod.
    metric-config.object.istio-requests-per-replica.prometheus/query: |
      sum(
          rate(
              istio_requests_total{
                destination_service_name="go-demo-7",
                destination_workload_namespace="go-demo-7",
                reporter="destination"
              }[1m]
          )
      ) /
      count(
        count(
          container_memory_usage_bytes{
            namespace="go-demo-7",
          pod_name=~"go-demo-7-primary.*"
          }
        ) by (pod_name)
      )
    # metric-config.object.istio-requests-error-rate.prometheus/per-replica: "true"
    metric-config.object.istio-requests-error-rate.prometheus/query: |
      sum(rate(istio_requests_total{destination_workload="go-demo-7-primary",
               destination_workload_namespace="go-demo-7", reporter="destination",response_code=~"5.*"}[1m])) 
      / 
      sum(rate(istio_requests_total{destination_workload="go-demo-7-primary", 
               destination_workload_namespace="go-demo-7",reporter="destination"}[1m]) > 0)* 100
      or
      sum(rate(istio_requests_total{destination_workload="go-demo-7-primary", 
               destination_workload_namespace="go-demo-7",reporter="destination"}[1m])) > bool 0 * 100
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-demo-7-primary
  metrics:
    - type: Object
      object:
        metricName: istio-requests-per-replica
        target:
          apiVersion: v1
          kind: Pod
          name: go-demo-7-primary
        targetValue: 5
    - type: Object
      object:
        metricName: istio-requests-error-rate
        target:
          apiVersion: v1
          kind: Pod
          name: go-demo-7-primary
        targetValue: 5