---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-7-app
  labels:
    app: go-demo-7-app
spec:
  selector:
    matchLabels:
      app: go-demo-7-app
  template:
    metadata:
      labels:
        app: go-demo-7-app
    spec:
      containers:
      - name: go-demo-7-app
        image: vfarcic/go-demo-7:0.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: DB
          value: go-demo-7-db
        - name: VERSION
          value: "0.0.1"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /demo/hello?health=true
            port: 8080
        readinessProbe:
          httpGet:
            path: /demo/hello?health=true
            port: 8080
        resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 25m
              memory: 64Mi
